version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TuPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: DiaTics2025WebApi/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DiaTics2025DB;User=sa;Password=TuPassword123!
    depends_on:
      - sqlserver

  blazor:
    build:
      context: .
      dockerfile: DiaTics2025/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - api

volumes:
  sql_data:
